### ISSUE TITLE
bug: package vulnerability interface should reuse `http.Client`

### ISSUE THREAD

**Issue by jhrozek** [stacklok/minder#1202]
At the moment the package vulnerability interface implementation (OSV and soon-to-be-added Pi) instantiate a `http.Client` on every call. This is wasteful, we should reuse a client to improve performance. We already do this via a simple map for the package database, we should do the same for the vulnerability interface, too.

**Comment by evankanderson** [comment]
We should measure whether this is actually a problem in practice.
