### ISSUE TITLE
remediate: support patching existing files in PRs

### ISSUE THREAD

**Issue by jhrozek** [stacklok/minder#1210]
The first version of PR remediations allows only replacing files. While this is acceptable as the PR would need to be reviewed by (hopefully) a human, having the ability to patch an existing file would be even better. We might want to consider:

- JSON merge patches as they are easy to use and read
- JSON patches (RFC 6902) as they allow appending to an array 
- conditional patches based on a JQ expressions (only patch if the expression returns true)

**Comment by evankanderson** [comment]
This should be part of a larger story improving PR rules.
