### ISSUE TITLE
Address remaining code review suggestions for the py requirements.txt parser

### ISSUE THREAD

**Issue by jhrozek** [stacklok/minder#1236]
**Describe the bug**
This issue is a reminder to address the open suggestions in PR #1225 

The suggestions should still be visible in the PR, but here's a short list:
- util.ParsePyRequirement(line string) (string, string)
- refactor the IndentedString() function - we might want to introduce a new struct that holds more context around what's being processed rather than just the new dep to cover cases like multiple version requirements 
- s/pyReqNormalizeLine/pyExtractAddedDeps/
- s/if len(match) < 3 {/if len(match) != util.PyRequestsVersionRegexp.NumSubexp() {/
- extract depName/versionString from the line, return these tuples instead of handling regex matches directly
- add a test for a removal

**Comment by evankanderson** [comment]
We've addressed these cleanups since.
