### ISSUE TITLE
Reuse the inline comments from the OSV checker to provide more in-context suggestions in a GitHub Pull Request

### ISSUE THREAD

**Issue by jhrozek** [stacklok/minder#1243]
Currently we have the OSV evaluator which is able to provide inline comments for PRs with vulnerabilities. I tried to reuse it for the initial implementation of the Pi integration, but it turned out that some refactoring is needed and the inline comments are currently too coupled to vulnerabilities. We should enable the inline comments code to also comment on policies that use the Pi evaluator.

(Probably) Depends on: #1203

**Comment by evankanderson** [comment]
We should do this in the following sprint
