### ISSUE TITLE
actions: move message templates to a separate package

### ISSUE THREAD

**Issue by rdimitrov** [stacklok/minder#1248]
The use of templates is probably going to raise with the implementation of more action types and other features where we present a given message so it would be useful if we have all of this in a standalone package for us to avoid repetition and be able to ensure correct behaviour in case of missing values, injection and proper rendering.

As per https://github.com/stacklok/mediator/pull/1232#issuecomment-1771518224.

Related: https://github.com/stacklok/mediator/issues/1242

**Comment by evankanderson** [comment]
We don't think this will get scheduled, but someone will come in and fix it when they're touching nearby code.  Removing this paperwork.
