### ISSUE TITLE
Filter policy status by evaluation status

### ISSUE THREAD

**Issue by jhrozek** [stacklok/minder#1262]
**Describe the bug**
With more complex policies I'm not interested in all of policy evaluation results, but more likely those that fail. It would be nice to be able to filter based on those that are not successful. Maybe even a generic JQ filter would be nice to allow users to construct their own filters (although we have -ojson piped to jq for that..)

**Comment by evankanderson** [comment]
This might be able to "go away" with the historical evaluation API.

@dmjb @blkt -- can we filter historical evaluation information to only "failing" resources?

**Comment by blkt** [comment]
Yes, it will be possible to filter by evaluation status, alert status, and remediation status.

**Comment by evankanderson** [comment]
It looks like we've added [`status` as a field on `ListEvaluationHistoryRequest`](https://github.com/stacklok/minder/blob/main/proto/minder/v1/minder.proto#L2572)
