### ISSUE TITLE
minder: improve enrolling a provider / registering a repository

### ISSUE THREAD

**Issue by rdimitrov** [stacklok/minder#1264]
**Describe the enhancement**
Currently we specify the org while enrolling a provider (using the `owner` flag) and we can register repos only from that org afterwards. 

If we want to register a repo from another org we'd have to re-enrol with the new one (this looses the ability to register repos from the prev. org enrolment).

**Expected behavior**

It would be better if we can enrol a provider once and then have the org (`owner`) flag used when we register repositories.

**Comment by evankanderson** [comment]
We've reworked this with the GitHub App
