### ISSUE TITLE
tests: Improve smoke tests

### ISSUE THREAD

**Issue by rdimitrov** [stacklok/minder#1278]
> Question: Do we want to add a Makefile target?

I think this can be a future task -- this gives us at least a bit of a framework to work with.

We might be able to leverage `GITHUB_TOKEN` from the GitHub API to enable login to mediator in staging, or we could store a secret with an auth token to mediator...

_Originally posted by @evankanderson in https://github.com/stacklok/mediator/issues/1268#issuecomment-1777274070_

**Comment by eleftherias** [comment]
@rdimitrov I think we can close this given all the work that's been done for smoke tests?

**Comment by rdimitrov** [comment]
@eleftherias - Definitely, thanks for finding it! 👍
