### ISSUE TITLE
Rename Metrics to Remove "github" Prefix for Generalization

### ISSUE THREAD

**Issue by teodor-yanev** [stacklok/minder#1436]
### Description
To ensure that our metrics names are generalized and do not provide a misleading representation of the data they capture, we need to rename the following metrics by removing the "github" part of their names:

**mediator_github_http_roundtrip_duration_milliseconds_bucket**
**mediator_github_http_roundtrip_duration_milliseconds_sum**
**mediator_github_http_roundtrip_duration_milliseconds_count**

### Rationale
The inclusion of "github" in these metrics names is misleading since they are intended to capture data for all outbound calls, not just those to GitHub. By renaming them, we ensure clarity and broader applicability of these metrics.

### Steps to Complete
1) Identify all locations in the code where these metrics are defined or called.
2) Rename the metrics as proposed above.
3) Update any related documentation or dashboards that reference these metrics.
4) Test to ensure that the new metric names are correctly capturing and displaying data.
5) Deploy changes to the relevant environments.

**Comment by eleftherias** [comment]
@teodor-yanev It look like this is intentionally GitHub specific. https://github.com/stacklok/minder/blob/7f4d1063fe27fbc51c8283258f91bb6a3c8d53a7/internal/providers/telemetry/telemetry.go#L94-L100

Presumably when we add more providers, we'll have a new metric for each provider.

**Comment by jhrozek** [comment]
so the histogram is per provider. Currently the only provider we support is GitHub, but if/when we support e.g. gitlab how would we want to handle that? (Honest question, I'm fine with anything)

**Comment by evankanderson** [comment]
I think we want separate metrics for each provider, failures from GitHub shouldn't be conflated with failures from e.g. DockerHub.
