### ISSUE TITLE
Pass in yes flag for minder cli commands that have a prompt message

### ISSUE THREAD

**Issue by rdimitrov** [stacklok/minder#1519]
It would be useful to pass in a 'yes' prompt (or no for that matter) when performing commands that have a confirmation prompt, i.e. `minder auth delete`.

**Comment by hemakshis** [comment]
Hi @rdimitrov 
I'd like to take up this issue. Since this is my first time here, would appreciate any help or pointers!

**Comment by JAORMX** [comment]
Hey @hemakshis ! We really appreciate you wanting to contribute! It's a little late in Europe where some of us are. But we'll get you more details tomorrow morning. Unless someone from the team works late today. Thanks again!

**Comment by rdimitrov** [comment]
> Hi @rdimitrov I'd like to take up this issue. Since this is my first time here, would appreciate any help or pointers!

Hey @hemakshis 👋 This is great, thanks for reaching out! 💯 

The goal of this issue is to implement a `--yes/-y` flag for some of the `minder` commands. The issue mentions also the option of adding a `--no/-n` flag, but let's leave that aside for now (but do share if you found a command where calling it with a `--no` flag would be valuable).

Here's some helpful information.

Implementation hints:
- Find all `minder` CLI commands that have prompts (use `cli.PrintYesNoPrompt()`) 
- Add the `--yes/-y` flag to each command that you found that make sense to have this as an optional flag
- Update each command implementation so it uses the value of the flag accordingly, i.e. skipping the prompts. 

References:
- Get familiar with our contributing guidelines - [here](https://github.com/stacklok/minder/blob/main/CONTRIBUTING.md)
- Minder uses two complementary frameworks for the CLI implementation - [cobra](https://github.com/spf13/cobra) and [viper](https://github.com/spf13/viper). You can check their docs/examples to get a sense of their usage.
- This is how a similar flag is added to a command - [here](https://github.com/stacklok/minder/blob/1ef32da674828a0bbbb408ea1a5b1fb30ab1582c/cmd/cli/app/rule_type/rule_type_delete.go#L148C2-L148C88)
- This is how you can use its value - [here](https://github.com/stacklok/minder/blob/1ef32da674828a0bbbb408ea1a5b1fb30ab1582c/cmd/cli/app/rule_type/rule_type_delete.go#L43)
- This is how you can make decisions based on its value - [here](https://github.com/stacklok/minder/blob/1ef32da674828a0bbbb408ea1a5b1fb30ab1582c/cmd/cli/app/rule_type/rule_type_delete.go#L78)

Feel free to reach out if I've missed something or you have any questions 👍

**Comment by hemakshis** [comment]
Thanks @rdimitrov for such detailed info, I will try it out and let you know how it goes on Monday :)

**Comment by hemakshis** [comment]
Hi @rdimitrov 
I have created https://github.com/stacklok/minder/pull/1730, please review 🙂
