### ISSUE TITLE
Add metrics on User-Agent values

### ISSUE THREAD

**Issue by JAORMX** [stacklok/minder#1532]
It is useful for us to know what clients are being used to access minder-server. We should have metrics that help us reflect this and make decisions.

**Comment by jhrozek** [comment]
@JAORMX @rdimitrov do we have the metrics though? We do send the user-agent, but we didn't add any counter did we?

**Comment by rdimitrov** [comment]
You're right, I thought this was covered in the PR. I'll reopen this 👍

**Comment by evankanderson** [comment]
We have this in the telemetry logs now.
