### ISSUE TITLE
read-only images can't update fulcio roots 

### ISSUE THREAD

**Issue by jhrozek** [stacklok/minder#1589]
**Describe the bug**
We're running our container images with read-only root. This means we get an error while attempting to update trust roots:
```
2023/11/08 07:20:06 error verifying image: error getting fulcio roots: initializing tuf: creating cached local store: mkdir /home/nonroot/.sigstore: read-only file system
```

**To Reproduce**
unsure

**Expected behavior**
we should check if we can point the code to use a different location that we would then mount an emptyDir over

**Comment by rdimitrov** [comment]
Closing as fixed by #1611
