### ISSUE TITLE
Implement context for minder CLI - be able to create, set, delete and work within a certain context

### ISSUE THREAD

**Issue by rdimitrov** [stacklok/minder#1750]

**Comment by JAORMX** [comment]
@rdimitrov what did this refer to?

**Comment by rdimitrov** [comment]
@JAORMX - The idea is to have the option to set a context for all consecutive minder commands. The context would be i.e. user, project, provider, etc. and every command that you run afterwards would be executed within this context without needing to specify these values explicitly.

**Comment by evankanderson** [comment]
Discussion on Discord: https://discordapp.com/channels/1184987096302239844/1185287949240242258/1187401023640326164

TL;DR: we might simply be able to use `viper` more intentionally and not need new code.

**Comment by rdimitrov** [comment]
We decided to handle multiple context by leveraging the features we already have through viper. Basically each context would be a new config file that can be specified via the `--config` flag. One can specify different minder and identity servers, but also cli generic variables such as `provider`, `project`, `output` formatting, etc. Variables which are flagged as required are not read from the config, even though they are bound to viper. This is because cobra expects those flags to passed and the viper value does not take precedence in this case. We can revisit this if a need for specifying, I.e. the profile name as part of the context makes sense for someone. Until then we can consider this issue as completed.

**Comment by evankanderson** [comment]
Reading through this a bit more, it seems like maybe adding an environment variable (either directly pointing to the file, or pointing to a directory with `.AddConfigPath` could be helpful.  I'm putting together a PR to do that.
