### ISSUE TITLE
Enable autocompletion and suggestions for the minder CLI

### ISSUE THREAD

**Issue by rdimitrov** [stacklok/minder#1753]

**Comment by JAORMX** [comment]
What do we need for this one? cobra already comes with auto-completion support enabled by default:

```bash
minder completion -h
```

**Comment by JAORMX** [comment]
The basic completion is covered by cobra's defaults already. If we have nice ideas on auto-completion use cases, let's open dedicated issues for those. e.g. it would be neat if the CLI auto-completed flags for project IDs automagically.

**Comment by rdimitrov** [comment]
Closed in favour of https://github.com/stacklok/minder/issues/1872 and https://github.com/stacklok/minder/issues/1874
