### ISSUE TITLE
Revisit and rename all command flags accordingly so they are consistent

### ISSUE THREAD

**Issue by rdimitrov** [stacklok/minder#1758]

**Comment by JAORMX** [comment]
@rdimitrov I don't remember what this one was about? Can you add more description?

**Comment by rdimitrov** [comment]
@JAORMX - Of course 👍 It's about making sure all flags have the same long and short name across all commands, i.e. things like `project` and `project-id`.

**Comment by JAORMX** [comment]
ah! got it! thanks
