### ISSUE TITLE
Revisit and update the "minder artifact" command, i.e. show more meaningful output

### ISSUE THREAD

**Issue by rdimitrov** [stacklok/minder#1762]

**Comment by jhrozek** [comment]
@rdimitrov so far I'm thinking about these changes:

* for artifact list:
  - add a `from` switch that would currently only support `=repository=owner/name`, e.g. `artifact list --from=repository=jakubtestorg/testrepo`. This would be extensible for the future if we ever add support for artifacts from registries
* for artifact get:
 - get the artifact by name. I guess simply owner/repo/artifact_name, the point is to just pass a string in the protobuf and deal with it on the server side
 - add a table output (might be done after your PR) which would be the default. Also JSON and YAML output as for other commands
 - in the table output, add whether there is a verified signature as unicode characters like for profile status
 - maybe filter by tags?
 - maybe filter by signature OK/not OK?

Does that sound good to you?

**Comment by rdimitrov** [comment]
@jhrozek - Sounds great! 👍 Perhaps one more thing - should we make the signed part a bit more informational. For example if the artifact is signed show the entity that signed it (the action) along with a date when that happened.

**Comment by jhrozek** [comment]
Since there are already quite a few issues around CLI, let's just use a list here:
 - [ ] artifact list by repo
 - [ ] artifact get by name
 - [ ] artifact get table
 - [ ] artifact get verified signature and signing entity
 from the above list, filter by tags was already there.
