### ISSUE TITLE
Make the quickstart YesNoPrompt default to "Yes"

### ISSUE THREAD

**Issue by andresgalante** [stacklok/minder#1764]
The new quickstart is a fantastic onboarding experience ❤️ It doesn't only handhold users through the setting up process but also teaches what commands are being executed.

The YesNoPrompt defaults to `No`, forcing users to choose `Yes` on every step instead of just hitting enter. 

Wouldn't it be better if the prompt defaults to yes instead?

**Comment by rdimitrov** [comment]
Hey, @andresgalante 👋 We addressed this in https://github.com/stacklok/minder/pull/1698, but we haven't released yet. Thanks for bringing this up so we can cut a release with the fix 👍

**Comment by rdimitrov** [comment]
Now that v0.0.19 is released, this should be fixed. Feel free to reopen if needed 👍
