### ISSUE TITLE
Docs: Getting started section is confusing

### ISSUE THREAD

**Issue by andresgalante** [stacklok/minder#1766]
Since the quickstart allows users to enroll, register repos, and create profiles, the getting started sections should probably be organized in a different way.

Would it be ok if I give it a try?

**Comment by rdimitrov** [comment]
Of course 💯

**Comment by evankanderson** [comment]
Hey, @andresgalante -- closing this as part of our bug triage, but feel free to come back and send a PR for anything that you're still finding confusing.
