### ISSUE TITLE
Add smoke test for checking repository status

### ISSUE THREAD

**Issue by eleftherias** [stacklok/minder#1780]
This also sets up a way to make requests as an authenticated user in an automated way.

- [ ] Retrieve a token for a user that is registered in staging (suggestion: save a long lived refresh token for stacklok bot in GitHub Actions and fetch a new access token on every run)
- [ ] Test that the profile status returns several rows and no errors
- [ ] Document how to get a long lived refresh token
- [ ] Document how to revoke a token in case it's compromised

**Comment by rdimitrov** [comment]
Closing this as Done since we already test it 👍
