### ISSUE TITLE
repo delete should also remove the webhook

### ISSUE THREAD

**Issue by lukehinds** [stacklok/minder#1783]
### Describe the issue

when deleting a repo, the webhook is left intact. 

this means a repo has been removed from minder, yet minder will still recieve webhook payload events for the deleted repo.

the webhook should be removed as well. 

https://docs.github.com/en/rest/repos/webhooks?apiVersion=2022-11-28#delete-a-repository-webhook

### To Reproduce

1. register a repo `minder repo register --provider github`
2. delete some repo `minder repo delete  --provider github --name lukehinds/some-repo`

After deleting, check the webhook setttings on the GitHub UI:

https://github.com/lukehinds/some-repo/settings/hooks

### What version are you using?

0.0.19

**Comment by Vyom-Yadav** [comment]
@lukehinds Please assign this issue to me.
