### ISSUE TITLE
`repo register --repo` should skip an already registered repository

### ISSUE THREAD

**Issue by jhrozek** [stacklok/minder#1826]
### Describe the issue

When a repository is already registered and a user tries to run `minder repo register --repo owner/name --provider=github` again, the command says that the repo can't be found and presents the user with a list of not-yet-registered repositories to choose from. Instead, it should just exit gracefully.

### To Reproduce

1. enroll a provider
2. register a repository
3. try to register the same repository again using the `--repo` switch

**Comment by Vyom-Yadav** [comment]
/assign

@jhrozek Please assign this to me if there is no bot.

**Comment by JAORMX** [comment]
@Vyom-Yadav done! Thanks for looking into this
