### ISSUE TITLE
Enable runtime autocompletion of arguments in minder

### ISSUE THREAD

**Issue by rdimitrov** [stacklok/minder#1874]
Cobra allows to have runtime autocompletion of arguments. This will be very nice to have since it will improve the UX of the CLI and minder in general.

**Example:**
In case of double-tab on

`minder profile delete`

 the user will be presented with a list of its profiles they can choose and autocomplete on - 

`minder-profile-1   quickstart-profile`

**Caveat:**

The caveat here is that it seems we use flags for everything, so this will imply changing some of the flags to arguments.

**References:**

* https://blog.devgenius.io/shell-completion-with-cobra-and-go-c8368074d8f7

**Comment by evankanderson** [comment]
This would be a lot of work; I suspect we want to apply that work elsewhere.
