### ISSUE TITLE
DEADLINE_EXCEEDED

### ISSUE THREAD

**Issue by AGMETEOR** [stacklok/minder#1932]
### Describe the issue

I keep getting the error in the screenshot below when I try to enroll my repos
<img width="1792" alt="Screenshot 2023-12-14 at 1 23 45 PM" src="https://github.com/stacklok/minder/assets/28563179/5ebaebd8-f586-46a1-903d-b8ed02957974">

### What version are you using?

No config file present, using default values. Version: 0.0.20 Go Version: go1.21.4 Git Commit: 0272289f474238c275434f7718a45eaa02133e3a Commit Date: 2023-12-08T08:39:46Z OS/Arch: darwin/amd64 Dirty: false User Agent: minder-cli/0.0.20 (darwin) amd64 (go1.21.4)

**Comment by jhrozek** [comment]
@AGMETEOR thank you for filing the issue! I was hitting the same problem yesterday, too and opened https://github.com/stacklok/minder/pull/1924 to address it. I need to go back to that PR and fix a lint issue. I'll do it ASAP and report when the bug was fixed and a new release tagged.

**Comment by AGMETEOR** [comment]
Thanks a lot @jhrozek . In the meantime, I have increased the context deadline from source and built a new binary. Maybe I also could have used a config file.

**Comment by jhrozek** [comment]
> Thanks a lot @jhrozek . In the meantime, I have increased the context deadline from source and built a new binary. Maybe I also could have used a config file.

Just note that if you build from source, then minder will point to stacklok's staging instance (the release binaries point to prod instance of minder). You can set the minder instance by setting `grpc_server.host` to `api.stacklok.com` for prod, though.

**Comment by AGMETEOR** [comment]
> > Thanks a lot @jhrozek . In the meantime, I have increased the context deadline from source and built a new binary. Maybe I also could have used a config file.
> 
> Just note that if you build from source, then minder will point to stacklok's staging instance (the release binaries point to prod instance of minder). You can set the minder instance by setting `grpc_server.host` to `api.stacklok.com` for prod, though.

Using my built binary, `minderbin` doing `./minderbin auth login` gives me 
```
Minder Server    api.stacklok.com:443
```

Is `api.stacklok.com:443` the staging server?

**Comment by JAORMX** [comment]
`api.stacklok.com` is prod

**Comment by AGMETEOR** [comment]
So my building from source also points to prod?

**Comment by JAORMX** [comment]
@AGMETEOR it depends on how you built it. I think you might have used goreleaser to build it, so that would end up in prod, which is anyway the right thing (staging is meant to be unstable)

**Comment by AGMETEOR** [comment]
I used `go build -o minderbin cmd/cli/main.go`

**Comment by JAORMX** [comment]
@AGMETEOR I was about to do a correction. Yeah, we default to production, and only point to staging if you'd do `make build`. So, building with `go build` directly will point to production.

I will open an issue to document this better, I had already forgotten :smile:

**Comment by JAORMX** [comment]
Here's the issue https://github.com/stacklok/minder/issues/1933

**Comment by AGMETEOR** [comment]
Can I work on it?

**Comment by JAORMX** [comment]
@AGMETEOR of course!

**Comment by AGMETEOR** [comment]
Do we have some web UI, apart from CLI where I can view profiles associated with my github provider?

**Comment by JAORMX** [comment]
@AGMETEOR there is no UI yet, only the CLI is available. It will be worked on in the near future though!

By default there are no profiles available in your project, you need to install them. We have a set of references in https://github.com/stacklok/minder-rules-and-profiles

**Comment by AGMETEOR** [comment]
Meanwhile `minder profile get -i <fdfdfd>` doesn't seem to be working. I keep getting `INVALID_ARGUMENT`

**Comment by JAORMX** [comment]
@AGMETEOR checking this out.

**Comment by JAORMX** [comment]
@AGMETEOR is this one still an issue for you?

**Comment by JAORMX** [comment]
@AGMETEOR thank you for the patience!! Sorry about the bumpy road

**Comment by AGMETEOR** [comment]
@JAORMX no problem. I think it should be fixed now. I just have one more thing I am trying to do using the quickstart guide. I already setup a repo for minder and I have a secret scanning rule setup by quickstart. What happens after that? Does minder comment on my repo or PR since I don't think I have secret scanning enabled on the repo.

**Comment by JAORMX** [comment]
@AGMETEOR actually, the quickstart's default profile will set things up in such a way that you'll get that fixed automatically.

The profile looks as follows:

```yaml
version: v1
type: profile
name: quickstart-profile
context:
  provider: github
alert: "on"
remediate: "on"
repository:
  - type: secret_scanning
    def:
      enabled: true
```

If for some reason your repos would be out of compliance, you'll see a GitHub security advisory. But it will also automatically fix it. So... most likely you just won't see issues, you'll just get the fix and minder will be happy. If you disable secret scanning, Minder will re-enable it given that it's the policy. That's controllable via the `remediate` toggle.

**Comment by AGMETEOR** [comment]
@JAORMX I see it now. I had disabled secret scanning on a repo but I had not checked again to see if minder had indeed renabled it. But it actually did. Perhaps I should get some sort of feedback (maybe through email) from minder to tell me what it actually did. Like in this case an alert that it enabled secret scanning. I can see "alert: on" but I didn't get one

**Comment by AGMETEOR** [comment]
> @AGMETEOR that is a good idea! Perhaps we could try to gather all the remediations done and present a summary. It gets tricky not to do too much noise, especially on more thorough profiles such as this one: https://github.com/stacklok/minder-rules-and-profiles/blob/main/profiles/github/stacklok-profile-remediate.yaml
> 
> I'll bring this up and see what the team comes up with! Thanks a lot for the feedback!

I think a summary would be nice. Thanks a lot for the engagement.

**Comment by rdimitrov** [comment]
Closing the issue as it was addressed by https://github.com/stacklok/minder/pull/1924 and https://github.com/stacklok/minder/issues/1935. Thanks again for bringing this up! 🙏
