### ISSUE TITLE
`minder profile get -i <fdfdfd>` results in an error.

### ISSUE THREAD

**Issue by JAORMX** [stacklok/minder#1935]
Per @AGMETEOR's comment:

Meanwhile `minder profile get -i <fdfdfd>` doesn't seem to be working. I keep getting `INVALID_ARGUMENT`
```
Error getting profile: Code: 3
Name: INVALID_ARGUMENT
Description: Invalid argument
Details: InvalidArgument indicates client specified an invalid argument.
```

_Originally posted by @AGMETEOR in https://github.com/stacklok/minder/issues/1932#issuecomment-1855784907_

**Comment by JAORMX** [comment]
@AGMETEOR working on this now.

**Comment by AGMETEOR** [comment]
Seems it has to be fixed from the server itself. Is the server code also open source?

**Comment by rdimitrov** [comment]
> Seems it has to be fixed from the server itself. Is the server code also open source?

Yes, it's in `cmd/server` 👍

**Comment by AGMETEOR** [comment]
> > Seems it has to be fixed from the server itself. Is the server code also open source?
> 
> Yes, it's in `cmd/server` 👍

Gotcha

**Comment by JAORMX** [comment]
We have a hypothesis of what's causing this issue. A potential fix will be posted soon.

**Comment by AGMETEOR** [comment]
Let me ask this here since it's related to the fix. Is there a make target to generate `minder.pb.go`?

**Comment by rdimitrov** [comment]
> Let me ask this here since it's related to the fix. Is there a make target to generate `minder.pb.go`?
Answered in https://github.com/stacklok/minder/pull/1936#discussion_r1426730074

**Comment by JAORMX** [comment]
@AGMETEOR the fix is in prod now.

**Comment by JAORMX** [comment]
> Let me ask this here since it's related to the fix. Is there a make target to generate `minder.pb.go`?

you can run `make buf` or `make gen` (`gen` will run all code generators)

**Comment by AGMETEOR** [comment]
> @AGMETEOR the fix is in prod now.

Confirmed it's now working. Thanks for the fix.
