### ISSUE TITLE
PR commented on multiple times

### ISSUE THREAD

**Issue by jhrozek** [stacklok/minder#1949]
### Describe the issue

We sometimes add multiple comments that tell that minder has analysed a PR. We should only be adding one and there already should be a safeguard looking for a magic comment in the previous PR but that is apparently not working correctly.

### To Reproduce

Unsure yet, but manifested at https://github.com/stacklok/minder/pull/1790#pullrequestreview-1785254837

### What version are you using?

today's master (stacklok staging)

**Comment by gregfurman** [comment]
Going to try and recreate this locally. Perhaps this has something to do with the force pushes?
cc @eleftherias

**Comment by eleftherias** [comment]
Thanks @gregfurman! Feel free to reach out if you have any questions.

**Comment by gregfurman** [comment]
@JAORMX should we close this in favour of https://github.com/stacklok/minder/issues/1862?

**Comment by JAORMX** [comment]
Sure!

Closing this issue in favor of https://github.com/stacklok/minder/issues/1862
