### ISSUE TITLE
A fresh repo cannot be remediated with branch protections

### ISSUE THREAD

**Issue by jhrozek** [stacklok/minder#1992]
### Describe the issue

This was spotted by Luke some time ago. When someone creates a completely empty repo, there's no branch. And since there's no branch we can't set branch protections

### To Reproduce

- Enroll GitHub namespace to minder
- Create a profile with branch protections
- Create an empty repo
- Enroll the repo with minder
- There are no branch protections

**Comment by JAORMX** [comment]
@jhrozek I don't think this is still an issue. At least remediations seem to work. Should we close this?

**Comment by jhrozek** [comment]
> @jhrozek I don't think this is still an issue. At least remediations seem to work. Should we close this?

Interesting, let me test this. We hit this issue not that long ago in December, so if this was fixed, I would assume a change in GitHub. btw the reason there was no branch protection possible to set was that in a fresh repo there might be no branch, depending on how you create the repo

**Comment by JAORMX** [comment]
@jhrozek ah! If there is no branch then yeah, this is still an issue then. I tested on a repo with no branch protections at all, but with a branch set.
