### ISSUE TITLE
Introduce versioned docs

### ISSUE THREAD

**Issue by rdimitrov** [stacklok/minder#2004]
The idea is to introduce versioned docs so we can:
* match the Minder releases. This way both are consistent, i.e. v0.0.21 of minder corresponds to v0.0.21 of docs 
* have the latest state of the docs available for everyone online that is not using an official release.

**Comment by evankanderson** [comment]
This would be hard, so we're going to punt until we're making largely-incompatible changes.  We _might_ mention versions on specific pages if necessary.
