### ISSUE TITLE
Remove superadmin role

### ISSUE THREAD

**Issue by eleftherias** [stacklok/minder#2070]
This role is not practically used, since it is never set in our identity provider.
There are still some instances where it's used for testing.

**Comment by rdimitrov** [comment]
@eleftherias - If I'm correct this should be completed by #2063, so we can close it. Do reopen if needed 👍

**Comment by eleftherias** [comment]
@rdimitrov It's not completely removed yet. We still use it for testing in some places, for example: https://github.com/stacklok/minder/blob/65fee552113796b7567ac2e9bd699acadad19c9a/internal/controlplane/handlers_oauth_test.go#L146
