### ISSUE TITLE
Allow one-shot fixes without full auto-remediation

### ISSUE THREAD

**Issue by JAORMX** [stacklok/minder#2182]
### Please describe the enhancement

As a user I'd like to tell minder to fix the issues it finds on my pipeline. However, I don't want to enable auto-remediation.

### Solution Proposal

I'd like to have a way to do one-shot fixes. e.g.

```
minder profile remediate <profile name>
```

which will trigger a reconciliation that issues the needed fixes. Without turning remediations on.

**Comment by jhrozek** [comment]
cc @dmjb this is definitely not a first issue, but it might be one to cut your teeth on as you get more familiar with the codebase

**Comment by mesembria** [comment]
We will probably end up doing this as part of an epic, given the scope of the work.
