### ISSUE TITLE
Add minder project list command

### ISSUE THREAD

**Issue by eleftherias** [stacklok/minder#2255]
Now that a user can belong to multiple projects, we should give them a way to see which projects they are a part of by adding a command like `minder project list`.

Currently it is possible to see the list of projects using the `minder auth whoami` command, but it would be nice to have it more discoverable.

Related to: #2227

**Comment by JAORMX** [comment]
I'll take this one as it ties very well into relying more on OpenFGA for project relationships. I'll take this as part of that work.

**Comment by JAORMX** [comment]
@puerco if it helps, this would require:
* Creating a new `ProjectService` GRPC service in the protobuf
* Implementing the new `ProjectService` in the Minder control plane (adding the new method).
* Adding the service to the list of allowed services in the helm chart's ingress.
To do the actual implementation, I'd suggest looking into the methods available in the authz client. There, you should be able to figure out what projects a user has access to.

**Comment by JAORMX** [comment]
closed by https://github.com/stacklok/minder/pull/2558
