### ISSUE TITLE
Improve error message when user doesn't specify project

### ISSUE THREAD

**Issue by eleftherias** [stacklok/minder#2256]
When a user is a member of multiple projects, they must specify the project they want to act on when using CLI commands, because we cannot derive the default project.

Currently we get this error message:
```
$ minder repo list
WARNING: This build uses a test environment and may not be stable 
Message: Error listing repositories
Details: InvalidArgument indicates client specified an invalid argument.
```

We should explicitly tell the user that they need to supply a project argument:
```
$ minder repo list --project b60e0f72-878a-46b3-81e0-087e37ee9f7d
```

**Comment by JAORMX** [comment]
This was addressed in https://github.com/stacklok/minder/pull/2259
