### ISSUE TITLE
authz: as a security engineer I want to consider to move to casbin

### ISSUE THREAD

**Issue by yrobla** [stacklok/minder#236]
We currently have a builtin authentication and authorization system based on grpc interceptors, that works for simple use cases. It works for traditional user/pass and for simple RBAC. But if we start adding complexity, this code could early get messy. We could consider integration with casbin here: https://github.com/casbin
It is integrated with casdoor for identity management, that allows to use keycloak as provider: https://github.com/casdoor/casdoor

So that could be a good combination for authorization.

**Comment by JAORMX** [comment]
This is superseded by a wider epic
