### ISSUE TITLE
Revisit and drop the tables related to Artifacts

### ISSUE THREAD

**Issue by rdimitrov** [stacklok/minder#2368]
The topic if this issue is to:
* Drop the `Artifact Versions` table (no longer used)
* Drop the `Artifact` table (still used, so we have to analyse if it's still needed or can be dropped as well)

**Comment by JAORMX** [comment]
As @psekar pointed out in Discord, the versions table has been removed already. I don't think we should be deleting the artifacts table though. Let's close this.
