### ISSUE TITLE
Unable to enroll provider due to "no valid authentication credentials"

### ISSUE THREAD

**Issue by datosh** [stacklok/minder#2386]
### Describe the issue

As a first time user, after [installing the Minder CLI](https://docs.stacklok.com/minder/getting_started/install_cli), I must have taken a wrong turn and tried to execute `minder provider enroll` next, where I was presented with a rather cryptic error message:

```
Message: error getting authorization URL
Details: Unauthenticated indicates the request does not have valid
authentication credentials for the operation.
```

After a bit of re-reading the docs I was able to figure out that I had to do a `minder auth login` first.

Any chance the error message can be improved to guide the user to execute the correct step?

### To Reproduce

1. Download Minder CLI
2. Execute `minder provider enroll`

### What version are you using?

v0.0.30

**Comment by jhrozek** [comment]
@datosh also, thank you very much for trying out Minder! If there's any more friction issues or any other problems you ran into, don't hesitate to file them. Feel free to also ping us on Discord, we'll be happy to hear any feedback.

**Comment by evankanderson** [comment]
We now produce an error message that says:

```
Message: It seems you are logged out. Please run "minder auth login" first.
```
