### ISSUE TITLE
Create a GitHub App provider

### ISSUE THREAD

**Issue by eleftherias** [stacklok/minder#2520]
Create a GitHub App provider that implements the same traits as the current GitHub OAuth provider.

Below are some key implementation differences

### Acting user attributes
In the OAuth provider, the user details to include when creating a commit or PR come from the PAT.
In the GitHub App provider, the user details should correspond to the apps details, as described [in this discussion](https://github.com/orgs/community/discussions/24664) and [this section of the design doc](https://docs.google.com/document/d/1SvXgkaB8ffgD2VH9pQq8rabgV-8ow3T9oBRtgZFPGVY/edit#heading=h.40mrvec3qfxm).

### Listing repositories
To get a list of all repositories, the GitHub app will [fetch the list of repos](https://docs.github.com/en/rest/apps/installations?apiVersion=2022-11-28#list-repositories-accessible-to-the-app-installation) available to the installations associated with a given project.

### Credentials
A GitHub app will need to generate tokens based on the following:
- The installation ID of the GitHub organization we are querying.This will be stored in the Minder DB.
- The GitHub app ID for the Minder app. We get this when we create the GitHub app.
- The client secret (PEM file) which we will also generate when we create the GitHub app.
The instructions for generating an installation access token are available in the [GitHub documentation](https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/generating-an-installation-access-token-for-a-github-app).

There may be other APIs that are different between the OAuth app and the GitHub app. 

note: This issue does not include supporting the "Marketplace flow". For the scope of this issue, we should only add support for the UI / CLI initiated flow, where we know how to associate an installation ID to a project.

[Design document](https://docs.google.com/document/d/1SvXgkaB8ffgD2VH9pQq8rabgV-8ow3T9oBRtgZFPGVY/edit)

**Comment by evankanderson** [comment]
The provider will need a new table to store the installation IDs, and we'll need to be able to indicate the different providers.

If we associate each provider with a specific GitHub installation, we may need multiple providers in the same project, and a way to select which provider to use when registering a repo.
