### ISSUE TITLE
Use the correct remediation status while waiting for PR to be accepted

### ISSUE THREAD

**Issue by rdimitrov** [stacklok/minder#2526]
Currently when we have a PR remediation and it opens a PR, the remediation status is `Success` which is a bit confusing since we haven't really fixed the issue. Perhaps a more appropriate value is something like `Pending` or `Opened`.

* Note that alerts rely on this status, so updating it means we should also consider how this affects the actions engine and potentially the alerts executions too.

**Comment by puerco** [comment]
Fixing this in #2530 2530
