### ISSUE TITLE
Projects can be orphaned without an administrator

### ISSUE THREAD

**Issue by evankanderson** [stacklok/minder#2528]
### Describe the issue

In https://github.com/stacklok/minder/pull/2275/files#r1506378930, we discussed whether a project should be garbage collected if there are users assigned to non-admin roles, but no users with admin roles remain on the project after a `DeleteUser` callback from Keycloak.

Our current behavior is:

> They can't do much on it, they'd have to add a support ticket for us to fix it. I think this is acceptable since we don't just want to randomly remove projects from folks.

We should consider whether removing the project and the entities the project manages is more user-friendly, as it allows someone else to register the entities again with Minder without needing Stacklok intervention.

### To Reproduce

Create a project, share it with another user with `viewer` permission, and then delete the Keycloak account for the user who created the project (and was the sole admin).

**Comment by evankanderson** [comment]
I think we fixed this a couple times @rdimitrov 

@eleftherias is writing a test for this

**Comment by eleftherias** [comment]
Validated that this is fixed. The current behaviour is to delete the project, along with the user, if there are no other admins on the project. If there are other admins on the project, then the project doesn't get deleted.
