### ISSUE TITLE
Rule types and profile types are case sensitive

### ISSUE THREAD

**Issue by ethomson** [stacklok/minder#2594]
Rule type and profile names are case sensitive. You can have (eg) `my-profile` and `My-Profile` within the same project. This makes reasoning about them and identifying them difficult.

Rule type, profile, project, etc names should be case insensitive and case preserving.

**Comment by jhrozek** [comment]
Evan fixed this in e0edc36755bda745817741cc25f911592df1728b we just forgot to close the issue
