### ISSUE TITLE
Add "Display Name" attribute to project

### ISSUE THREAD

**Issue by dmjb** [stacklok/minder#2599]
### Please describe the enhancement

For the UI, it would be useful to have a human-friendly name for projects, which can be set by the customer. We do not want to reuse the current name field.

### Solution Proposal

A project should have a non-unique "Display Name" field. The API should allow this field to be set and retrieved. 

### Additional context

[UI issue for setup minder org step ](https://github.com/stacklok/minder-frontend/issues/60)

**Comment by ethomson** [comment]
I think this is projects, profiles, and rule types.

**Comment by JAORMX** [comment]
@ethomson you want a display name for profiles and rule types as well?

**Comment by ethomson** [comment]
I do. I want to show the results of the "OpenSSF Scorecard" in the UI, not "openssf-scorecard"

**Comment by JAORMX** [comment]
@ethomson let's create a separate issue for that. The semantics will differ.

**Comment by JAORMX** [comment]
Closed by https://github.com/stacklok/minder/pull/2705
