### ISSUE TITLE
Extend profile list endpoints to filter by profile labels (include and exclude)

### ISSUE THREAD

**Issue by dmjb** [stacklok/minder#2759]
### Please describe the enhancement

Labels were recently added to profiles. When profiles (and profile statuses) are listed through the API, we need to filter the results by label. We need the following types of filter:

1) "Only show profiles (or statuses) with label X"
2) "Show all profiles (or statuses) except those with label X"

For now, the label for the healthcheck will simply be `healthcheck`

### Solution Proposal

Modify the `ListProfiles` and `GetProfileStatusByProject` endpoints to accept query parameters, e.g.

`?with_label={label}`
`?exclude_label={label}`

We likely need additional DB queries to support this use case.

**Comment by jhrozek** [comment]
I forgot to include the proper fixes tags in the PR (I used related instead), so closing this one manually.
