### ISSUE TITLE
Move provider credentials under ProviderConfig

### ISSUE THREAD

**Issue by eleftherias** [stacklok/minder#2798]
Currently we have our GitHub provider credentials defined in the `server-config.yaml` like this:
```
github:
  client_id: X
  client_secret: Y
```
We fetch the credentials using viper directly:
https://github.com/stacklok/minder/blob/4524f991586d2b90603718364eef0a0068e85219/internal/auth/oauth.go#L121-L122

Since we now have the `ProviderConfig`, we should move the credentials there:
```
provider:
  github:
    client_id: X
    client_secret: Y
```
and refactor the oauth client to use the server configuration, instead of calling viper directly.

**Comment by jhrozek** [comment]
Pulling into the sprint - turns out that this is needed to handle configuration for the auto-enrollment in a sane way and keep the code testable.
