### ISSUE TITLE
GitHub App installation deleted event should remove webhooks

### ISSUE THREAD

**Issue by eleftherias** [stacklok/minder#2923]
As I was writing https://github.com/stacklok/minder/pull/2922 I realised that when an GitHub App is uninstalled, we should also remove any repository webhooks that were created by Minder.

**Comment by evankanderson** [comment]
Can we do this?  Won't we already have lost access to the repos?

(Otherwise, yes, we should do this; particularly on `delete provider` on our side)

**Comment by eleftherias** [comment]
That's true, we don't have permissions to delete the webhooks when we receive an event. We already do remove the webhooks on `delete provider` from the CLI.
