### ISSUE TITLE
Handle user deletion gracefully when the user created the organization

### ISSUE THREAD

**Issue by ethomson** [stacklok/minder#2948]
### Describe the issue

If you create an organization (top-level project), then it will be created with your GitHub username. You can then invite somebody to that organization, then delete your user account (minder auth delete). Your project will continue to exist, still named as your GitHub username. You now cannot even log in again, since doing so would create a new organization with your GitHub username, but one already exists.

### To Reproduce

1. Create a new user account (and thus a new project).
   `minder auth login`
   At this point, you will have a new Minder organization (top-level project) that is named after your GitHub username.
2. Invite someone else to your project
   `minder project role grant ...`
3. Delete your account
   `minder auth delete`

Now you can no longer create a new account (`minder auth login`). Creating your new account would try to create a new project with your GitHub username as the org name. However, that already exists (you orphaned it in step 2). You can no longer use Minder.

**Comment by evankanderson** [comment]
There is a workaround with the GitHub App flow if you start from https://github.com/apps/minder-by-stacklok (or whatever your app name is) to register the organizations in Minder before you create your account.  At that point, CreateUser will create projects for each pending App Install rather than the project named based on the user.

**Comment by evankanderson** [comment]
I'm also going to check in a small fix to remove the project when the last `admin` member is removed, rather than the last user, since a `viewer` or `editor` on the project can't recover full use of the project once there are no admins.

**Comment by evankanderson** [comment]
Looking at the code further, it seems like we actually remove the auth before the projects, which could lead to a second problem if the database transaction fails.  We probably need to rethink the flow here to be less all-at-once and more sequential.
