### ISSUE TITLE
Add structured way to return rule evaluations

### ISSUE THREAD

**Issue by jhrozek** [stacklok/minder#3097]
Currently the rule evaluations we returned are not really structured which is hard to consume from both scripts and clients like the minder UI.

We should come up with a way to return the results as structured parseable data.
![image (2)](https://github.com/stacklok/minder/assets/715522/5a860fa5-2498-49dd-ae21-a8100c11cea8)

**Comment by eleftherias** [comment]
@ethomson This seems like a duplicate of stacklok/minder-stories#3. I'm imagining the long detailed message would be a replacement for what is now in "issue reason".

**Comment by eleftherias** [comment]
After discussing with @rdimitrov @blkt @peppescg we determined that stacklok/minder-stories#3 is a better solution for the same problem.
