### ISSUE TITLE
Add external ID to Minder entities

### ISSUE THREAD

**Issue by dmjb** [stacklok/minder#3142]
### Please describe the enhancement

Per recent discussion on providers, add an external ID to artifacts and repositories. This will be an opaque identifier which the providers will use to identify the entity in the third party API.

### Solution Proposal

Per discussion with Evan - store the ID information in a protobuf, serialize, and store in the DB.

**Comment by evankanderson** [comment]
@dmjb -- I think we may be doing this somewhere else.  Do you want to link this in, or close it?
