### ISSUE TITLE
Improve `minder project role grant` flow

### ISSUE THREAD

**Issue by evankanderson** [stacklok/minder#3150]
The long-term goal is to allow users to run:

```
minder project role grant -r editor -s github:evankanderson
```

for a project, rather than:

```
minder project role grant -r editor -s 2a351c66-c276-4231-9d21-bfbd3d5babb5
```

Where `2a351c66-c276-4231-9d21-bfbd3d5babb5` is a user ID which can't be looked up the grantor, and can only be found by running `minder auth whoami` as the user receiving the grant.

This has three phases:

* [x] #3151
* [x] #3152
* [x] #3153
  * The user will still need to accept the terms of service when they log in, but their Keycloak account should already be created when they first access Minder.

**Comment by eleftherias** [comment]
@evankanderson Do you think this can be closed now that we have the email invite flow?

**Comment by evankanderson** [comment]
Yes, thank you!
