### ISSUE TITLE
The trusty evaluator can only comment

### ISSUE THREAD

**Issue by jhrozek** [stacklok/minder#3165]
It would be nice if it could also block like the OSV evaluator

**Comment by puerco** [comment]
I've started looking into this

**Comment by jhrozek** [comment]
> I've started looking into this

Let me know if you want to chat. tl;dr I think the whole trusty and OSV providers are ripe for a major refactoring and I'd love to bounce ideas with someone. I remember we talked about how Minder handles dependencies so I'm sure you have some ideas as well :-)

**Comment by puerco** [comment]
I'll close this issue as the trusty evaluator can now block through reviews since https://github.com/stacklok/minder/issues/3379
