### ISSUE TITLE
Add a ReconcileEntityRegistration method to the Providers API and a reconcile repository implementation to the GitHub App

### ISSUE THREAD

**Issue by jhrozek** [stacklok/minder#3268]
In order to trigger repository reconciliation to either cover the case where we miss a webhook or after the initial enablement of the auto-enrollment we need a way to tell the provider to reconcile the auto-registered repositories with the upstream repositories.

To do that, we'd extend the providers API with an ReconcileEntityRegistration method exposed as an RPC. The Github app provider would implement it to reconcile repositories.

The RPC might look like this:
```
rpc ReconcileEntityRegistration (ReconcileEntityRegistrationRequest) returns (ReconcileEntityRegistrationResponse) {
        option (google.api.http) = {
            post: "/api/v1/provider/{provider}/register_all"
            additional_bindings {
                post: "/api/v1/provider/register_all",
                body: "*"
            }
            body: "*"
        };

        option (rpc_options) = {
            target_resource: TARGET_RESOURCE_PROJECT
	     // TODO: ensure that we either have per-entity APIs or we have a relation that allows any entity
            relation: RELATION_REPO_CREATE
        };
    }

message ReconcileEntityRegistrationRequest {
    Context context = 1;
    Entity entity = 2; // reconcile this entity type only
}

message RegisterRepositoryResponse {
	// empty by design
}

```

**Comment by jhrozek** [comment]
Inside the handler I think we could do the following:
 - extract the code from `ListRepositoriesFromProvider` inside the `	for providerName, provider := range provs` to a reusable function in the server to get the list of repositories that are not registered yet.
 - for every repo that is not registered, create a message using `s.repositoryAdded()`
 - dispatch the message as we do for the auto-registration messages with `HandleGitHubAppWebhook`.

I think this would be OK for a start. We need to then have a way to signal to the reconcile handler to stop if a token is below certain threshold, but I suggest we file a separate ticket for that.

@blkt do you agree with the above?

**Comment by blkt** [comment]
I agree, we should have a single code path for registration hooked into multiple entry points (i.e. `minder repo register`, automatic registration, etc...).

> We need to then have a way to signal to the reconcile handler to stop if a token is below certain threshold

I studied this subject a bit in the past, in particular I'd love to apply feedback control to this. Definitely worth another issue!

**Comment by jhrozek** [comment]
> > We need to then have a way to signal to the reconcile handler to stop if a token is below certain threshold
> 
> I studied this subject a bit in the past, in particular I'd love to apply feedback control to this. Definitely worth another issue!

If you know what to do here, it would be great to base the implementation on your experience - feel free to file a ticket and add it to epic #31!

**Comment by teodor-yanev** [comment]
Changing the paths to:

`"/api/v1/provider/{provider}/register_all"`
`"/api/v1/provider/register_all"`

to make them provider-specific and generalise the entity that will come as a param from the request.

**Comment by teodor-yanev** [comment]
One more thing: The provider as a path parameter is now deprecated. We are adding it as a compatibility option but fetching it from the `Context` is preferred.

**Comment by jhrozek** [comment]
> [@teodor-yanev](https://github.com/teodor-yanev) mentioned that this HTTP path should be used instead `/api/v1/provider/register_all`, but I can't figure out if its in the `additional_bindings` or not.

I don't think we need to use the addinonal bindings - sorry, that was a copy-pasta on my part. We should just use the `post` path. (For more context, the additional bindings were used as a backwards-compatibility help when we were switching to provider-in-context)
