### ISSUE TITLE
Add artifact enrollment for dockerhub

### ISSUE THREAD

**Issue by JAORMX** [stacklok/minder#3326]
### Please describe the enhancement

This proposes adding an artifact registration workflow to minder.

### Solution Proposal

This proposes adding an `artifact register` subcommand which will register an artifact or container for dockerhub into minder.

### Additional context

This is needed because dockerhub doesn't have the ability to get events for artifacts being added or removed, so we need to explicitly track them in minder

**Comment by evankanderson** [comment]
We did a spike on this; when we revisit the DockerHub provider, we'll re-plan based on our current architecture.
