### ISSUE TITLE
Create an event handler for invitations - publish/subscribe

### ISSUE THREAD

**Issue by rdimitrov** [stacklok/minder#3618]
Copied from a previous issue (perhaps not really up-to-date, but still worth keeping):

> Build an optional event listener to send emails -- this could be closed-source
> 
> - This will need a Stacklok-customized email template delivered to Minder, probably as a volume mount (additional image?)
> - We will use Amazon SES (Simple Email Service) to start with, but should aim to modularize sending email

**Comment by JAORMX** [comment]
Just from the title, is it so that we'll have an event listener that will get events from Minder and do the actual AWS calls? If so, are we sure we want to have a publish/subscribe model for this? We probably want to get some status ASAP and a REST or gRPC interface might be more appropriate.
