### ISSUE TITLE
Create mock evaluation history API for frontend dev/testing

### ISSUE THREAD

**Issue by dmjb** [stacklok/minder#3671]
This API endpoint will return stubbed data to allow the FE team to make progress. This endpoint will not follow the expected final API contract - e.g. it will not support pagination and filtering.

**Comment by blkt** [comment]
API spec is already on staging environment, it was done in #3558, while real data will be available once #3746 is merged (currently under review).
I'm closing this issue, feel free to reopen if necessary.
