### ISSUE TITLE
Generate and provide invite URL

### ISSUE THREAD

**Issue by rdimitrov** [stacklok/minder#3727]

**Comment by nitishmalang** [comment]
i want to work on this issue please assign me

**Comment by rdimitrov** [comment]
> i want to work on this issue please assign me

hey, @nitishmalang, apologies, this is a mistake on my side because I missed to assign it and we've already started working on this. 

Nevertheless, we'll be happy to have you so you can have a look at the rest of the issues and pick one from there, there are ones labeled with `good-first-issue` as well. 

Feel free to ping us in Discord (https://discord.com/channels/1184987096302239844/1185287949240242258) to help you choose one 👍
