### ISSUE TITLE
RuleType to ensure credentials are structured with minimal permissions

### ISSUE THREAD

**Issue by puerco** [stacklok/minder#3840]
We should create a RuleType that checks that permissions in workflows are structured from a minimal grant and only increase them when needed.

**Comment by evankanderson** [comment]
Does https://github.com/stacklok/minder-rules-and-profiles/pull/135 address this?

I'm not sure how to specifically test that the grant is _minimal_ today, but the above at least ensures that the grant is _explicit_, which feels like it's been helpful in the past.  Something like http://github.com/step-security/harden-runner might be a future integration to further reduce permissions.

**Comment by puerco** [comment]
Yes I added your rule to comply with this requirement in the [baseline profile](https://github.com/stacklok/minder-rules-and-profiles/pull/136) in the minder way. I think we can close this now.
