### ISSUE TITLE
investigate the OTEL breakage

### ISSUE THREAD

**Issue by jhrozek** [stacklok/minder#4534]
We've had issues lately with otel upgrades. This issue is filed to track that we spent time investigating where the issue is and hopefully record the outcome.

Assigning to @blkt who already spent time doing that but -- @blkt please don't feel pressured to work on this unless you already planned on.

**Comment by blkt** [comment]
I managed to narrow down the issue to some extent and wrote a minimal script to reproduce.
https://github.com/blkt/panicrepro
I also opened an issue in the repo that I guess is responsible for the bug, although I'm not 100% sure.
https://github.com/signalfx/splunk-otel-go/issues/3430

**Comment by blkt** [comment]
This is confirmed as a regression on `otel` libraries.
https://github.com/open-telemetry/opentelemetry-go/pull/5828

We'll probably have to close all PRs from dependabot for those libraries until a new version is released, as it looks like there's no workaround to the problem.
