### ISSUE TITLE
ci: as a developer I want my version of sqlc files to automatically bump when sqlc is bumped

### ISSUE THREAD

**Issue by yrobla** [stacklok/minder#487]
We have dependabot automatically filling upgrades when sqlc version is bumped. But those CI jobs fail because the version of sqlc in the generated files, is different than the new one that dependabot proposed. We will want some automation , either in dependabot, or in a next PR, to automatically bump the version of the generated sql files when sqlc version bumps.

**Comment by evankanderson** [comment]
We don't bump `sqlc` often enough to worry about this right now.
