### ISSUE TITLE
Projects foundation using new domain model

### ISSUE THREAD

**Issue by lukehinds** [stacklok/minder#542]
While https://github.com/stacklok/mediator/pull/539 added an initial database schema for projects, we need to hook this up to mediator server and use it for both tenancy management and authorization.

[# Tenancy Management](https://docs.google.com/document/d/10TqSJFEoJSwB2U3_Z4_c6-yf8a6BPJFN5YNy7uV9E18/edit#heading=h.het0307bwprm) gives a notion of how projects should behave. Ideally we should allow users to create sub-projects and list sub-nodes in the project tree. We should also change our authorization logic to traverse the tree and make decisions on top of that.

Finally, the logic of policies and rules will need to change to accommodate for the new hierarchical view of the world.

# User RBAC

From an API perspective we should allow the following:

* A user should be able to list the projects/sub-projects they have access to.
* A user should be able to get information of projects/sub-projects they have access to (GET).
* A user should be able to create sub-projects in a given project (create node with parent).
* A user should be able to delete a sub-project.

Our current RBAC constructs might or might not be enough for this, so we should revisit what we have and see if it accommodates for these use-cases. IMO, creating sub-projects is a fairly privileged operation, but shouldn't require full admin privileges.

Full admin privileges should be required for a use-case as follows:

* An administrator should be able to create a root project (node with no parent).

Access should be granted via "Role Assignments", that is, a link between a specific role, a user and a node in the project tree.

# Object/Tree relationships

With a hierarchical view of the world, object relationships should go as follows:

* Entities (build environments, artifacts and repositories) should be accessible to projects and sub-projects for a given allowed user. That is, `allow (current_project + getChildren(current_project)` given that the user is allowed access to `current_project`.

* Rule Types and Policies (Pipeline Policies?) are accessible by all children of the given node they exist in. That is, Any user with read access to rule types and policies on child projects may view rule types and policies. Any user with write/create access for policies may use rule types that are created on parent nodes.

    - Modification of rule types and policies requires write access on the project they exist in.

* Policies apply to all entities existing within the child projects of the project the policy is applied in.

**Comment by JAORMX** [comment]
This has been addressed.
