### ISSUE TITLE
cli: minder apply should cover new entities

### ISSUE THREAD

**Issue by yrobla** [stacklok/minder#583]
**Describe the bug**
We currently have a minder apply command, that takes a yaml file and applies the result (similar as kubectl). However, it is only covering org, role, user and group entities. We should have feature parity with all the minder entities defined on the client. It would be ideal if the code could be improved, to get automatic coverage every time that we define a new entity, instead of having to manually modify the apply command code.

**Comment by JAORMX** [comment]
superseded by https://github.com/stacklok/minder/issues/1761
