### ISSUE TITLE
Return codes of 404 for unauthorized users may disclose data

### ISSUE THREAD

**Issue by yrobla** [stacklok/minder#662]
**Describe the bug**
We have several cases where users may query entities for an specific id:
```
group get --id 1
policy_type delete --id 2
```

In this case we need to search for the related entity in DB, to get its context (provider, group, org...) and only then we can check if the user is authorized or not.
But also in this check, we are returning a 404 error if the id is not found, even if the user is not authorized.
This may be the right thing to do , because we can inform the end user if it has some mistake with the ID it is using. But in the other hand, we may be informing an unauthorized user about this specific ID not existing, so it could be a security problem.
We need to discuss what's the best thing to do:
- return some unauthorized error in the case an id is not found
- continue doing as we do now, while we report a 404 when the id is wrong

Everything has pros/cons. We need to discuss about it and arrive to a decision to apply globally

**Comment by JAORMX** [comment]
This has been addressed.
