### ISSUE TITLE
feat: set a policy in "block" mode so if there is a policy violation, the associated task will be blocked from executing

### ISSUE THREAD

**Issue by dussab** [stacklok/minder#665]
**Is your feature request related to a problem? Please describe.**
Policy violations should block an action from executing therefore mitigating accidental software supply chain risk exposure.

**Describe the solution you'd like**
- Create rules via the CLI
- Create policy via the CLI
- Associate policy to a repository
- Set policy mode to "block" from the CLI
- Observe policy violation enforcement (blocked action)

**Acceptance Criteria**
- Create rules and polices related to Github repositories via the CLI 
- View rules and polices via the CLI
- Trigger a policy violation (misconfigure Github repository)
- List the policy violations via the CLI
- Fix the Github repository configuration so it adheres to the policy
- List the policy violations via the CLI and ensure there are no violations
- User documentation regarding the feature and usage 

**Related Epic**
stacklok/epics#3

**Comment by evankanderson** [comment]
Closing until we get a properly-scoped epic.
