### ISSUE TITLE
Predictable configuration path as a usability improvement

### ISSUE THREAD

**Issue by jhrozek** [stacklok/minder#679]
**Describe the bug**
I'm not sure this issue qualifies as a bug, but it doesn't seem big enough to warrant an epic. I'm filing it as a continuation and a permanent record of [a conversation](https://github.com/stacklok/mediator/pull/673#discussion_r1294589206) I had with Evan in PR #673.

At the moment, mediator expects the config file to be in the same directory from which the mediator binaries are executed. This is fine and actually comfortable for development, but much less for system-wide installs and while the commands allow for the config to be overridden, that would require e.g. setting up an alias.

**To Reproduce**
1. Install mediator system-wide, e.g. to /opt
2. Now the config needs to be placed in /opt as well

**Expected behavior**
A mechanism that allows setting up a per-user kubeconfig. Evan suggested to use a similar approach as kubectl's looking up kube config and I think it's a nice idea.

**Comment by evankanderson** [comment]
We did this.
