### ISSUE TITLE
cli: have a way to set the `--provider` value and avoid specifying it on each minder call

### ISSUE THREAD

**Issue by jhrozek** [stacklok/minder#687]
**Describe the bug**
This is just a UX/ease of use issue. At the moment we only support a single provider, yet many `minder` calls require to pass the provider explicitly. It might be useful, at least for developers to be able to pass e.g. an environment variable for the default provider.

**To Reproduce**
1. many `minder` invocations, e.g. `minder policy list --provider github`

**Expected behavior**
Set the default provider once. like `export MINDER_DEFAULT_PROVIDER=github`

**Comment by JAORMX** [comment]
this has already been addressed and we can close it.
