### ISSUE TITLE
feat: configurable artifact retention

### ISSUE THREAD

**Issue by jhrozek** [stacklok/minder#722]
**Describe the bug**
Tracking a follow-up from PR #692.

At the moment, the artifact retention is hardcoded to 30 days. This might not be ideal because:

- some projects might not even release every 30 days
- for others it might be too much (those that release after every commit? typically in a devops-like CI/CD pipeline)

it was suggested in the PR that limiting the number of artifacts might make more sense, but ultimately I think the artifact retention should be configurable. Creating rule pipelines could be handy here as one part of the pipeline could be defining artifact retention.

**Comment by evankanderson** [comment]
We've refactored this code substantially.
