### ISSUE TITLE
feat: on policy init, check the dependencies with git ingester

### ISSUE THREAD

**Issue by jhrozek** [stacklok/minder#839]
This is a follow-up to the vulnerability checking web hook-based flow. In order to support policy init and periodical reconcile, let's consume the whole package manifest (e.g. the whole go.mod or the whole package.json) using the git ingester and check its contents against a database like OSV.

The remediation in this case might be an issue or a PR.

**Comment by evankanderson** [comment]
This is a larger problem than an issue -- this would fit into the "drift detection" epic.

**Comment by evankanderson** [comment]
We have an epic tracking this, it will need more design before we can implement.

https://github.com/stacklok/epics/issues/157
