### ISSUE TITLE
tests: add race condition test case for signed versioned artifacts

### ISSUE THREAD

**Issue by rdimitrov** [stacklok/minder#936]
**Description**

The issue is about writing a test case that covers a race condition that sometime happens when we receive the web hook event for a signature before the actual artifact. 

The problem should be solved by https://github.com/stacklok/mediator/pull/932, but given the code base at that moment it is tricky to write a proper test case for it since it implies a significant refactoring of the code to enable proper mocking.

**Details**

I realise this might be a bit broader description of the test case but it implies prepping the environment by mocking a few DB calls used throughout the test, register the webhook handler to the queue and once we have this ready, execute the HTTP calls for each type (signature and artifact) in the correct and incorrect order to make sure we process them without any error and payload data is handled/stored as we expect.

Related to https://github.com/stacklok/mediator/pull/932

**Comment by evankanderson** [comment]
We've got this tracked elsewhere.
