### ISSUE TITLE
bug: webhook handlers convert all numerical types to float64

### ISSUE THREAD

**Issue by jhrozek** [stacklok/minder#965]
**Describe the bug**
Following up on code-review in pull #952. We use the JQ accessor function to read numerical types but always pass in float64 as the type. For some reason, the type conversion to other fixed-width numerical types like int32 or int64 fails. We should investigate and fix the code to convert to the types used by the GH API as otherwise we risk under or overflows.

**Comment by evankanderson** [comment]
We're replacing this code, and we already replaced most of this code.
