### ISSUE TITLE
Support lazy pagination for GitHub API

### ISSUE THREAD

**Issue by jhrozek** [stacklok/minder#996]
**Describe the bug**
Our GitHub API either doesn't support any pagination at all (and just hardcodes one page with the largest allowed size) or supports greedy pagination where everything is read at the same time in a single loop.

We should support lazy pagination, perhaps by returning a channel from the List functions that the consumer could read from. This would also allow for creating pipelines more easily.

For some reference, see PR #975 and the discussion there.

**Comment by evankanderson** [comment]
We will address this when we are adding pagination to our public APIs, or where we hit issues.  We probably won't come back and find this issue, and changing the public APIs to include pagination is probably not a "good first issue".
